name: simple CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run build
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Publish test report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'shallowSizePluginTest/build/test-results/test/TEST-*.xml'

      - name: Run detekt
        run: ./gradlew detekt
