name: simple CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run build
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Publish test report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          path: 'shallowSizePluginTest/build/test-results/test/'

      - name: Run detekt
        run: ./gradlew detekt
